name: 'export-env-action'
description: 'Exports .env file variables to job env'
author: 'cardinalby'
inputs:
  envFile:
    description: 'Path to .env file'
    required: true
  expand:
    description: 'Substitute ${VAR} references by values of correspondent vars'
    required: false
    default: 'false'
  export:
    description: |
      Export variables to a job environment. If `false`, all variables will be set as an action 
      outputs instead.
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - uses: cardinalby/js-eval-action@testPkg
      env:
        ENV_FILE: ${{ inputs.envFile }}
        EXPAND: ${{ inputs.expand }}
        EXPORT: ${{ inputs.export }}
      with:
        jsFile: ${{ github.action_path }}/index.js
        extractOutputs: 'true'