name: "test"
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  doNotExpand:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Do not export
        id: noExport
        uses: ./
        with:
          envFile: '.github/workflows/test/case1.env'
          export: 'false'

      - name: Check noExport result
        if: |
          env.AAA != '' || 
          env.BBB != ''
        run: >
          echo "env.AAA: '${{env.AAA}}'" && 
          echo "env.BBB: '${{env.BBB}}'" &&
          echo "steps.noExport.outputs.AAA: '${{steps.noExport.outputs.AAA}}'" &&
          echo "steps.noExport.outputs.BBB: '${{steps.noExport.outputs.BBB}}'" &&
          exit 1

      - name: Do not expand
        uses: ./
        with:
          envFile: '.github/workflows/test/case1.env'
          expand: 'false'

      - name: Check noExpand result
        if: env.AAA != 'aaa#a' || env.BBB != 'val-${AAA}-lav'
        run: exit 1

      - name: Load not exisitng
        id: nonExisting
        uses: ./
        continue-on-error: true
        with:
          envFile: '.github/workflows/test/case-non-existing.env'
          expand: 'false'

      - name: Check nonExisting result
        if: steps.nonExisting.outcome != 'failure'
        run: exit 1
  expandTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Do not export
        id: noExport
        uses: ./
        with:
          envFile: '.github/workflows/test/case1.env'
          export: 'false'
          expand: 'true'

      - name: Check noExport result
        if: |
          env.AAA != '' || 
          env.BBB != '' ||
          steps.noExport.outputs.AAA != 'aaa#a' ||
          steps.noExport.outputs.BBB != 'val-aaa#a-lav'
        run: exit 1

      - name: Expand
        uses: ./
        with:
          envFile: '.github/workflows/test/case1.env'
          expand: 'true'

      - name: Check expand result
        if: env.AAA != 'aaa#a' || env.BBB != 'val-aaa#a-lav'
        run: exit 1
  jsonTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: JSON test
        uses: ./
        with:
          envFile: '.github/workflows/test/case2.env'

      - name: Check JSON result
        if: env.json != ''
        run: exit 1