name: "test"
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  doNotExpandTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Do not expand
        uses: ./
        with:
          envFile: '.github/workflows/test/case1.env'
          expand: 'false'

      - name: Check noExpand result
        if: env.AAA != 'aaaa' || env.BBB != 'val-${AAA}-lav'
        run: exit 1

      - name: Load not exisitng
        id: nonExisting
        uses: ./
        continue-on-error: true
        with:
          envFile: '.github/workflows/test/case-non-existing.env'
          expand: 'false'

      - name: Check nonExisting result
        if: steps.nonExisting.outcome != 'failure'
        run: exit 1
  expandTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Expand
        uses: ./
        with:
          envFile: '.github/workflows/test/case1.env'
          expand: 'true'

      - name: Check expand result
        if: env.AAA != 'aaaa' || env.BBB != 'val-aaaa-lav'
        run: exit 1